export const allTriggerList = [
  {
    "trigger_id": 1,
    "en_name": "TP_trapezius 1",
    "ch_name": "斜方肌1号触发点",
    "tenton_quyu": "c6_L,c15_L,c21_L,c26_L,c33_L",
    "camera_params": "",
    "trigger_no": "CFD001",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 2,
    "en_name": "TP_trapezius 2",
    "ch_name": "斜方肌2号触发点",
    "tenton_quyu": "c29_L",
    "camera_params": "",
    "trigger_no": "CFD002",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 3,
    "en_name": "TP_trapezius 3",
    "ch_name": "斜方肌3号触发点",
    "tenton_quyu": "c29_L,c39_L,c37_L,c33_L",
    "camera_params": "",
    "trigger_no": "CFD003",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 4,
    "en_name": "TP_trapezius 4",
    "ch_name": "斜方肌4号触发点",
    "tenton_quyu": "c35_L",
    "camera_params": "",
    "trigger_no": "CFD004",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 5,
    "en_name": "TP_trapezius 5",
    "ch_name": "斜方肌5号触发点",
    "tenton_quyu": "c36_L,c37_L,c38_L",
    "camera_params": "",
    "trigger_no": "CFD005",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 6,
    "en_name": "TP_trapezius 6",
    "ch_name": "斜方肌6号触发点",
    "tenton_quyu": "c33_L",
    "camera_params": "",
    "trigger_no": "CFD006",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 7,
    "en_name": "TP_sternocleidomastoid_sternal branch",
    "ch_name": "胸锁乳突肌（胸骨部）触发点",
    "tenton_quyu": "c3_L,c4_L,c40_L,c12_L,c18_L,c22_L,c120_L",
    "camera_params": "",
    "trigger_no": "CFD007",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 8,
    "en_name": "TP_sternocleidomastoid_clavicular branch",
    "ch_name": "胸锁乳突肌（锁骨部）触发点",
    "tenton_quyu": "c23_L,c24_L,c1,c19_L",
    "camera_params": "",
    "trigger_no": "CFD008",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 9,
    "en_name": "TP_Levator scapulae",
    "ch_name": "肩胛提肌触发点",
    "tenton_quyu": "c32_L,c34_L",
    "camera_params": "",
    "trigger_no": "CFD009",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 10,
    "en_name": "TP_Splenius capitis",
    "ch_name": "头夹肌",
    "tenton_quyu": "c40_L",
    "camera_params": "",
    "trigger_no": "CFD010",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 11,
    "en_name": "TP_Splenius cervicis 1",
    "ch_name": "颈夹肌1号触发点",
    "tenton_quyu": "c6_L",
    "camera_params": "",
    "trigger_no": "CFD011",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 12,
    "en_name": "TP_Splenius cervicis 2",
    "ch_name": "颈夹肌2号触发点",
    "tenton_quyu": "c32_L",
    "camera_params": "",
    "trigger_no": "CFD012",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 13,
    "en_name": "TP_Sample semispinalis capitis 1",
    "ch_name": "头半棘肌1号触发点",
    "tenton_quyu": "c2_L,c14_L,c16_L,c41_L,c41_R,c27_R,c16_R,c2_R,c14_R,c27_L",
    "camera_params": "",
    "trigger_no": "CFD013",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 14,
    "en_name": "TP_Sample semispinalis capitis 2",
    "ch_name": "头半棘肌2号触发点",
    "tenton_quyu": "c27_L,c27_1_L,c28_L",
    "camera_params": "",
    "trigger_no": "CFD014",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 15,
    "en_name": "TP_Miltifidi and rotatores",
    "ch_name": "多裂肌和回旋肌触发点",
    "tenton_quyu": "c30_L,c31_L,c34_L,c35_L",
    "camera_params": "",
    "trigger_no": "CFD015",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 16,
    "en_name": "TP_Suboccipitals",
    "ch_name": "枕下肌群触发点",
    "tenton_quyu": "c15_L,c16_L,c17_L,c23_L",
    "camera_params": "",
    "trigger_no": "CFD016",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 17,
    "en_name": "TP_Temporalis",
    "ch_name": "颞肌触发点",
    "tenton_quyu": "c13_L,c14_L,c16_L,c9_L,c10_L",
    "camera_params": "",
    "trigger_no": "CFD017",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 18,
    "en_name": "TP_Masseter",
    "ch_name": "咬肌触发点",
    "tenton_quyu": "c3_L,c7_L,c10_L,c20_L,c18_L,c19_L",
    "camera_params": "",
    "trigger_no": "CFD018",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 19,
    "en_name": "TP_Medial pterygoid",
    "ch_name": "翼内肌触发点",
    "tenton_quyu": "c18_L",
    "camera_params": "",
    "trigger_no": "CFD019",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 20,
    "en_name": "TP_Lateral pterygoid",
    "ch_name": "翼外肌触发点",
    "tenton_quyu": "c18_L,c7_L",
    "camera_params": "",
    "trigger_no": "CFD020",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 21,
    "en_name": "TP_Digastric",
    "ch_name": "二腹肌触发点",
    "tenton_quyu": "c25_L,c11_L",
    "camera_params": "",
    "trigger_no": "CFD021",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 22,
    "en_name": "TP_Buccinator",
    "ch_name": "颊肌触发点",
    "tenton_quyu": "c10_L",
    "camera_params": "",
    "trigger_no": "CFD022",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 23,
    "en_name": "TP_Obicularis oculi",
    "ch_name": "眼轮匝肌触发点",
    "tenton_quyu": "c3_L,c4_L,c5_L,c8_L",
    "camera_params": "",
    "trigger_no": "CFD023",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 24,
    "en_name": "TP_Zygomaticus and levator labii",
    "ch_name": "颧肌和提上唇肌触发点",
    "tenton_quyu": "c4_L,c5_L,c7_L",
    "camera_params": "",
    "trigger_no": "CFD024",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0001"
  },
  {
    "trigger_id": 25,
    "en_name": "TP_Scalene ",
    "ch_name": "斜角肌触发点",
    "tenton_quyu": "x3_L,x5_L,x11_L,x13_L,x14_L,x15_L,x35_L,x36_L,x34_L,x32_L,x24_L,x19_L,x20_L,c36_L,c37_L",
    "camera_params": "",
    "trigger_no": "CFD025",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 26,
    "en_name": "TP_Rhomboid",
    "ch_name": "菱形肌触发点",
    "tenton_quyu": "c36_L,c37_L,c38_L",
    "camera_params": "",
    "trigger_no": "CFD026",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 27,
    "en_name": "TP_Serratus posterior superior",
    "ch_name": "上后锯肌触发点",
    "tenton_quyu": "s1_L,c36_L,s4_L,s18_L,s19_L,x23_L,x27_L,x30_L",
    "camera_params": "",
    "trigger_no": "CFD027",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 28,
    "en_name": "TP_Supraspinatus",
    "ch_name": "冈上肌触发点",
    "tenton_quyu": "x14_L,s18_L,s19_L",
    "camera_params": "",
    "trigger_no": "CFD028",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 29,
    "en_name": "TP_Infraspinatus",
    "ch_name": "冈下肌触发点",
    "tenton_quyu": "x10_L,x12_L,x14_L,c36_L,c37_L,c38_L",
    "camera_params": "",
    "trigger_no": "CFD029",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 30,
    "en_name": "TP_Teres minor",
    "ch_name": "小圆肌触发点",
    "tenton_quyu": "s3_ST_L,s3_SZ_L",
    "camera_params": "",
    "trigger_no": "CFD030",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 31,
    "en_name": "TP_Subscapularis",
    "ch_name": "肩胛下肌触发点",
    "tenton_quyu": "s2_ST_L,s2_SZ_L,s3_ST_L,s3_SZ_L,x17_L",
    "camera_params": "",
    "trigger_no": "CFD031",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 32,
    "en_name": "TP_Deltoid",
    "ch_name": "三角肌触发点",
    "tenton_quyu": "x11_L,x14_L,s4_L",
    "camera_params": "",
    "trigger_no": "CFD032",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 33,
    "en_name": "TP_Teres major and TP_Latissimus dorsi",
    "ch_name": "大圆肌和背阔肌触发点",
    "tenton_quyu": "s4_L,s7_L,s8_L,s13_L,c38_L",
    "camera_params": "",
    "trigger_no": "CFD033",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 34,
    "en_name": "TP_Coracobrachialis",
    "ch_name": "喙肱肌触发点",
    "tenton_quyu": "x10_L,s5_L,x16_L,_L,x21_L,x25_L,x28_L",
    "camera_params": "",
    "trigger_no": "CFD034",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 35,
    "en_name": "TP_Biceps",
    "ch_name": "肱二头肌触发点",
    "tenton_quyu": "x10_L",
    "camera_params": "",
    "trigger_no": "CFD035",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 36,
    "en_name": "TP_Triceps number 1",
    "ch_name": "肱三头肌1号触发点",
    "tenton_quyu": "s3_ST_L,s3_SZ_L,s18_L",
    "camera_params": "",
    "trigger_no": "CFD036",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 37,
    "en_name": "TP_Triceps number 2",
    "ch_name": "肱三头肌2号触发点",
    "tenton_quyu": "s18_L",
    "camera_params": "",
    "trigger_no": "CFD037",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 38,
    "en_name": "TP_Triceps number 3",
    "ch_name": "肱三头肌3号触发点",
    "tenton_quyu": "s4_L",
    "camera_params": "",
    "trigger_no": "CFD038",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 39,
    "en_name": "TP_Triceps number 4",
    "ch_name": "肱三头肌4号触发点",
    "tenton_quyu": "s19_L",
    "camera_params": "",
    "trigger_no": "CFD039",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 40,
    "en_name": "TP_Triceps number 5",
    "ch_name": "肱三头肌5号触发点",
    "tenton_quyu": "s19_L,s20_L",
    "camera_params": "",
    "trigger_no": "CFD040",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0002"
  },
  {
    "trigger_id": 41,
    "en_name": "TP_Brachialis",
    "ch_name": "肱肌触发点",
    "tenton_quyu": "x35_L",
    "camera_params": "",
    "trigger_no": "CFD041",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 42,
    "en_name": "TP_Extensor carpi radialis longus、TP_Brachioradialis、TP_Extensor indicis",
    "ch_name": "桡侧腕长伸肌、肱桡肌和旋后肌触发点",
    "tenton_quyu": "x15_L,x19_L,s18_L",
    "camera_params": "",
    "trigger_no": "CFD042",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 43,
    "en_name": "TP_Extensor carpi radialis brevis",
    "ch_name": "桡侧腕短伸肌  ",
    "tenton_quyu": "x18_L,x20_L,x21_L,x22_L",
    "camera_params": "",
    "trigger_no": "CFD043",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 44,
    "en_name": "TP_Extensor carpi ulnaris",
    "ch_name": "尺侧腕伸肌",
    "tenton_quyu": "x23_L",
    "camera_params": "",
    "trigger_no": "CFD044",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 45,
    "en_name": "TP_Anconeus",
    "ch_name": "肘肌",
    "tenton_quyu": "s18_L",
    "camera_params": "",
    "trigger_no": "CFD045",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 46,
    "en_name": "TP_Extensor digitorum and TP_Extensor indicis",
    "ch_name": "指伸肌和示指伸肌触发点",
    "tenton_quyu": "s18_L,x25_L,x26_L,x20_L,x24_L",
    "camera_params": "",
    "trigger_no": "CFD046",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 47,
    "en_name": "TP_Abductor pollicus longus sample",
    "ch_name": "拇指伸肌和拇指展肌触发点（拇长展肌）",
    "tenton_quyu": "x37_L,x38_L,x40_L,x28_L,x29_L",
    "camera_params": "",
    "trigger_no": "CFD047",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 48,
    "en_name": "TP_Flexor carpi radialis",
    "ch_name": "桡侧腕屈肌触发点",
    "tenton_quyu": "x37_L",
    "camera_params": "",
    "trigger_no": "CFD048",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 49,
    "en_name": "TP_Flexor carpi ulnaris",
    "ch_name": "尺侧腕屈肌触发点",
    "tenton_quyu": "x23_L",
    "camera_params": "",
    "trigger_no": "CFD049",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 50,
    "en_name": "TP_Palmaris longus",
    "ch_name": "掌长肌触发点",
    "tenton_quyu": "x33_L,x34_L",
    "camera_params": "",
    "trigger_no": "CFD050",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 51,
    "en_name": "TP_Flexor digitorum",
    "ch_name": "指屈肌触发点",
    "tenton_quyu": "x28_L,x29_L,x30_L",
    "camera_params": "",
    "trigger_no": "CFD051",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 52,
    "en_name": "TP_Pronator teres and pronator quadratus",
    "ch_name": "旋前圆肌和旋前方肌触发点",
    "tenton_quyu": "x37_L,x38_L,x39_L,x23_L,x27_L,x30_L,x28_L,x29_L,x31_L",
    "camera_params": "",
    "trigger_no": "CFD052",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 53,
    "en_name": "TP_Flexor pollicis longus",
    "ch_name": "拇长屈肌触发点",
    "tenton_quyu": "x36_L",
    "camera_params": "",
    "trigger_no": "CFD053",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 54,
    "en_name": "TP_Opponens pollicis",
    "ch_name": "大鱼际肌触发点（拇对掌肌）",
    "tenton_quyu": "x36_L,x37_L,x28_L,x35_L,x38_L,x32_L,x34_L,x19_L,x40_L,x15_L",
    "camera_params": "",
    "trigger_no": "CFD054",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 55,
    "en_name": "TP_adductor pollicis",
    "ch_name": "拇收肌触发点",
    "tenton_quyu": "x35_L,x34_L",
    "camera_params": "",
    "trigger_no": "CFD055",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 56,
    "en_name": "",
    "ch_name": "小指展肌触发点",
    "tenton_quyu": "",
    "camera_params": "",
    "trigger_no": "CFD056",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 57,
    "en_name": "TP_dorsal  interosseous ",
    "ch_name": "骨间肌触发点",
    "tenton_quyu": "x28_L,x29_L,x30_L,x24_L,x20_L,x21_L,x22_L,x23_L,x27_L",
    "camera_params": "",
    "trigger_no": "CFD057",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0003"
  },
  {
    "trigger_id": 58,
    "en_name": "TP_pectoralis major,clavicular section",
    "ch_name": "胸大肌（锁骨部）触发点",
    "tenton_quyu": "x9_ST_L,x9_SZ_L,x10_L",
    "camera_params": "",
    "trigger_no": "CFD058",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 59,
    "en_name": "TP_pectoralis major,sternal section",
    "ch_name": "胸大肌（胸骨部）触发点",
    "tenton_quyu": "x3_L,x4_L,x5_L,x6_L,x7_L",
    "camera_params": "",
    "trigger_no": "CFD059",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 60,
    "en_name": "TP_Pectoralis major, costal section",
    "ch_name": "胸大肌（肋骨部）触发点",
    "tenton_quyu": "x7_L,x8_L",
    "camera_params": "",
    "trigger_no": "CFD060",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 61,
    "en_name": "TP_subclavius",
    "ch_name": "锁骨下肌触发点",
    "tenton_quyu": "x1_L,x12_L,x15_L",
    "camera_params": "",
    "trigger_no": "CFD061",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 62,
    "en_name": "TP_Sample sternalis",
    "ch_name": "胸骨肌触发点",
    "tenton_quyu": "x1_L,x2_L",
    "camera_params": "",
    "trigger_no": "CFD062",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 63,
    "en_name": "TP_Pectoralis minor ",
    "ch_name": "胸小肌触发点",
    "tenton_quyu": "x9_ST_L,x9_SZ_L,x10_L",
    "camera_params": "",
    "trigger_no": "CFD063",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 64,
    "en_name": "TP_Serratus anterior ",
    "ch_name": "前锯肌触发点",
    "tenton_quyu": "s13_L,s8_L",
    "camera_params": "",
    "trigger_no": "CFD064",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 65,
    "en_name": "TP_Diaphragm",
    "ch_name": "膈肌触发点",
    "tenton_quyu": "f1_L",
    "camera_params": "",
    "trigger_no": "CFD065",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 66,
    "en_name": "TP_Upper abdominal ",
    "ch_name": "上腹肌触发点",
    "tenton_quyu": "f1_L",
    "camera_params": "",
    "trigger_no": "CFD066",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 67,
    "en_name": "TP_Midabdominal",
    "ch_name": "中腹肌触发点",
    "tenton_quyu": "f3_L,f4_L",
    "camera_params": "",
    "trigger_no": "CFD067",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 68,
    "en_name": "TP_Lower abdominal ",
    "ch_name": "下腹肌触发点",
    "tenton_quyu": "f6_L,f5_L",
    "camera_params": "",
    "trigger_no": "CFD068",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 69,
    "en_name": "TP_Abdominal",
    "ch_name": "腹肌触发点",
    "tenton_quyu": "s9_L,s10_L,s14_L,s15_L",
    "camera_params": "",
    "trigger_no": "CFD069",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 70,
    "en_name": "TP_Psoas and iliacus ",
    "ch_name": "腰大肌和髂肌触发点",
    "tenton_quyu": "s10_L,s12_L,s15_L,s17_L,f2_L,f3_L,f5_L,f10_L",
    "camera_params": "",
    "trigger_no": "CFD070",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0004"
  },
  {
    "trigger_id": 71,
    "en_name": "TP_Deep spinal muscles",
    "ch_name": "脊柱深层肌触发点",
    "tenton_quyu": "c36_L,c37_L,c38_L,s10_L,s12_L,s15_L,s17_L",
    "camera_params": "",
    "trigger_no": "CFD071",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 72,
    "en_name": "TP_Longissimus",
    "ch_name": "最长肌触发点 ",
    "tenton_quyu": "s7_L,c38_L,k1_L,k9_L",
    "camera_params": "",
    "trigger_no": "CFD072",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 73,
    "en_name": "TP_Iliocostalis",
    "ch_name": "髂肋肌触发点",
    "tenton_quyu": "k3_L,s14_L,s16_L,_L",
    "camera_params": "",
    "trigger_no": "CFD073",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 74,
    "en_name": "TP_Serratus posterior inferior",
    "ch_name": "下后锯肌触发点",
    "tenton_quyu": "s9_L,s10_L,s11_L,s12_L",
    "camera_params": "",
    "trigger_no": "CFD074",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 75,
    "en_name": "TP_Quadratus lumborum superficial ",
    "ch_name": "腰方肌外侧触发点",
    "tenton_quyu": "k8_L,k7_L",
    "camera_params": "",
    "trigger_no": "CFD075",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 76,
    "en_name": "TP_Quadratus lumborum deep",
    "ch_name": "腰方肌内侧触发点",
    "tenton_quyu": "k4_L,k8_L",
    "camera_params": "",
    "trigger_no": "CFD076",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 77,
    "en_name": "TP_Gluteus maximus number 1",
    "ch_name": "臀大肌1号触发点",
    "tenton_quyu": "k9_L,k5_ST_L,k5_SZ_L,k5_ST_R,k7_L",
    "camera_params": "",
    "trigger_no": "CFD077",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 78,
    "en_name": "TP_Gluteus maximus number 2 ",
    "ch_name": "臀大肌2号触发点",
    "tenton_quyu": "k4_L,k8_L,k9_L",
    "camera_params": "",
    "trigger_no": "CFD078",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 79,
    "en_name": "TP_Gluteus maximus number 3",
    "ch_name": "臀大肌3号触发点",
    "tenton_quyu": "k6_L",
    "camera_params": "",
    "trigger_no": "CFD079",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 80,
    "en_name": "TP_Gluteus medius number 1",
    "ch_name": "臀中肌1号触发点",
    "tenton_quyu": "k3_L,k8_L,k9_L,k1_L,k4_L,k7_L",
    "camera_params": "",
    "trigger_no": "CFD080",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 81,
    "en_name": "TP_Gluteus medius number 2",
    "ch_name": "臀中肌2号触发点",
    "tenton_quyu": "k3_L,k8_L,k9_L,k12_L",
    "camera_params": "",
    "trigger_no": "CFD081",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 82,
    "en_name": "TP_Gluteus medius number 3",
    "ch_name": "臀中肌3号触发点",
    "tenton_quyu": "k3_L,k4_L,k5_ST_L,k5_SZ_L,k5_ST_R,k6_L",
    "camera_params": "",
    "trigger_no": "CFD082",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 83,
    "en_name": "TP_Gluteus minimus number 1 ",
    "ch_name": "臀小肌1号触发点",
    "tenton_quyu": "k8_L,k18_L,k19_L",
    "camera_params": "",
    "trigger_no": "CFD083",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 84,
    "en_name": "TP_Gluteus minimus number 2",
    "ch_name": "臀小肌2号触发点",
    "tenton_quyu": "k9_L,k12_L,k16_L,k17_L",
    "camera_params": "",
    "trigger_no": "CFD084",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 85,
    "en_name": "TP_Piriformis number 1 ",
    "ch_name": "梨状肌1号触发点 ",
    "tenton_quyu": "_L",
    "camera_params": "",
    "trigger_no": "CFD085",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 86,
    "en_name": "TP_Piriformis number 2",
    "ch_name": "梨状肌2号触发点",
    "tenton_quyu": "k4_L",
    "camera_params": "",
    "trigger_no": "CFD086",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0005"
  },
  {
    "trigger_id": 87,
    "en_name": "TP_Tensor fasciae latae",
    "ch_name": "阔筋膜张肌触发点",
    "tenton_quyu": "k18_L,k7_L",
    "camera_params": "",
    "trigger_no": "CFD087",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 88,
    "en_name": "TP_Sartorius",
    "ch_name": "缝匠肌触发点",
    "tenton_quyu": "f7_SZ_L,f4_ST_L,f8_ST_L,f8_SZ_L,f11_L,f12_L",
    "camera_params": "",
    "trigger_no": "CFD088",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 89,
    "en_name": "TP_Rectus femoris number 1 ",
    "ch_name": "股直肌1号触发点",
    "tenton_quyu": "f13_L",
    "camera_params": "",
    "trigger_no": "CFD089",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 90,
    "en_name": "TP_Rectus femoris number 2",
    "ch_name": "股直肌2号触发点",
    "tenton_quyu": "f13_L",
    "camera_params": "",
    "trigger_no": "CFD090",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 91,
    "en_name": "TP_Vastus intermedius",
    "ch_name": "股中间肌触发点",
    "tenton_quyu": "f10_L",
    "camera_params": "",
    "trigger_no": "CFD091",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 92,
    "en_name": "TP_Vastus medialis number 1 ",
    "ch_name": "股内侧肌1号触发点",
    "tenton_quyu": "f15_L",
    "camera_params": "",
    "trigger_no": "CFD092",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 93,
    "en_name": "TP_Vastus medialis number 2",
    "ch_name": "股内侧肌2号触发点",
    "tenton_quyu": "f12_L",
    "camera_params": "",
    "trigger_no": "CFD093",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 94,
    "en_name": "TP_Vastus lateralis number 1",
    "ch_name": "股外侧肌1还触发点",
    "tenton_quyu": "f13_L",
    "camera_params": "",
    "trigger_no": "CFD094",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 95,
    "en_name": "TP_Vastus lateralis number 2",
    "ch_name": "股外侧肌2还触发点",
    "tenton_quyu": "k18_L",
    "camera_params": "",
    "trigger_no": "CFD095",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 96,
    "en_name": "TP_Vastus lateralis number 3",
    "ch_name": "股外侧肌3还触发点",
    "tenton_quyu": "k12_L",
    "camera_params": "",
    "trigger_no": "CFD096",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 97,
    "en_name": "TP_Vastus lateralis number 4",
    "ch_name": "股外侧肌4还触发点",
    "tenton_quyu": "k18_L",
    "camera_params": "",
    "trigger_no": "CFD097",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 98,
    "en_name": "TP_Vastus lateralis number 5",
    "ch_name": "股外侧肌5还触发点",
    "tenton_quyu": "k8_L",
    "camera_params": "",
    "trigger_no": "CFD098",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 99,
    "en_name": "TP_Pectineus",
    "ch_name": "耻骨肌触发点",
    "tenton_quyu": "f8_ST_L,f8_SZ_L",
    "camera_params": "",
    "trigger_no": "CFD099",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 100,
    "en_name": "TP_Adductors longus and brevis ",
    "ch_name": "长收肌和短收肌触发点",
    "tenton_quyu": "f7_SZ_L,f4_ST_L,f13_L",
    "camera_params": "",
    "trigger_no": "CFD100",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 101,
    "en_name": "TP_Adductor magnus number 1 ",
    "ch_name": "大收肌1号触发点",
    "tenton_quyu": "f9_L",
    "camera_params": "",
    "trigger_no": "CFD101",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 102,
    "en_name": "TP_Adductor magnus number 2",
    "ch_name": "大收肌2号触发点",
    "tenton_quyu": "f11_L,f8_ST_L,f8_SZ_L,f12_L",
    "camera_params": "",
    "trigger_no": "CFD102",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 103,
    "en_name": "TP_Gracilis ",
    "ch_name": "股薄肌触发点",
    "tenton_quyu": "f11_L",
    "camera_params": "",
    "trigger_no": "CFD103",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 104,
    "en_name": "TP_Biceps femoris ",
    "ch_name": "股二头肌触发点",
    "tenton_quyu": "k13_L,k14_L",
    "camera_params": "",
    "trigger_no": "CFD104",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 105,
    "en_name": "TP_Semitendinosus and semimembranosus ",
    "ch_name": "半腱肌和半膜肌触发点",
    "tenton_quyu": "_L",
    "camera_params": "",
    "trigger_no": "CFD105",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 106,
    "en_name": "TP_Popliteus",
    "ch_name": "腘肌触发点",
    "tenton_quyu": "k13_L,k14_L",
    "camera_params": "",
    "trigger_no": "CFD106",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 107,
    "en_name": "TP_Plantaris",
    "ch_name": "跖肌触发点",
    "tenton_quyu": "k13_L,k14_L",
    "camera_params": "",
    "trigger_no": "CFD107",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0006"
  },
  {
    "trigger_id": 108,
    "en_name": "TP_Tibialis anterior ",
    "ch_name": "胫骨前肌触发点",
    "tenton_quyu": "d10_L,d12_L",
    "camera_params": "",
    "trigger_no": "CFD108",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 109,
    "en_name": "TP_Extensor digitorum longus ",
    "ch_name": "趾长伸肌触发点",
    "tenton_quyu": "d8_L,d9_L",
    "camera_params": "",
    "trigger_no": "CFD109",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 110,
    "en_name": "TP_Extensor hallucis longus ",
    "ch_name": "长伸肌触发点",
    "tenton_quyu": "d12_L",
    "camera_params": "",
    "trigger_no": "CFD110",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 111,
    "en_name": "TP_Peroneus longus",
    "ch_name": "腓骨长肌触发点",
    "tenton_quyu": "k20_L",
    "camera_params": "",
    "trigger_no": "CFD111",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 112,
    "en_name": "TP_Peroneus brevis",
    "ch_name": "腓骨短肌触发点",
    "tenton_quyu": "k20_L,d5_L",
    "camera_params": "",
    "trigger_no": "CFD112",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 113,
    "en_name": "TP_Peroneus tertius",
    "ch_name": "第三腓骨肌触发点",
    "tenton_quyu": "d2_L,d6_L",
    "camera_params": "",
    "trigger_no": "CFD113",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 114,
    "en_name": "TP_Gastrocnemius number 1",
    "ch_name": "腓肠肌1号触发点",
    "tenton_quyu": "d20_L,d13_L,d14_L",
    "camera_params": "",
    "trigger_no": "CFD114",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 115,
    "en_name": "TP_Other gastrocnemius",
    "ch_name": "腓肠肌其他触发点",
    "tenton_quyu": "k14_L,k15_L,k16_L",
    "camera_params": "",
    "trigger_no": "CFD115",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 116,
    "en_name": "TP_Soleus number 1 ",
    "ch_name": "比目鱼肌1号触发点",
    "tenton_quyu": "k16_L,k17_L",
    "camera_params": "",
    "trigger_no": "CFD116",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 117,
    "en_name": "TP_Soleus number 2",
    "ch_name": "比目鱼肌2号触发点",
    "tenton_quyu": "d22_L,d21_L,d23_L",
    "camera_params": "",
    "trigger_no": "CFD117",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 118,
    "en_name": "TP_Soleus number 3",
    "ch_name": "比目鱼肌3号触发点",
    "tenton_quyu": "k2_L",
    "camera_params": "",
    "trigger_no": "CFD118",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 119,
    "en_name": "TP_Soleus number 4",
    "ch_name": "比目鱼肌4号触发点",
    "tenton_quyu": "d6_L",
    "camera_params": "",
    "trigger_no": "CFD119",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 120,
    "en_name": "TP_Tibialis posterior",
    "ch_name": "胫骨后肌触发点",
    "tenton_quyu": "d22_L,d1_L,d24_L",
    "camera_params": "",
    "trigger_no": "CFD120",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 121,
    "en_name": "TP_Flexor digitorum longus ",
    "ch_name": "趾长屈肌触发点",
    "tenton_quyu": "d16_L,d17_L",
    "camera_params": "",
    "trigger_no": "CFD121",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 122,
    "en_name": "TP_Flexor hallucis longus ",
    "ch_name": "长屈肌触发点",
    "tenton_quyu": "d12_L,d15_L,d18_L",
    "camera_params": "",
    "trigger_no": "CFD122",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 123,
    "en_name": "TP_Extensor digitorum brevis and extensor hallucis",
    "ch_name": "趾短伸肌和短伸肌触发点",
    "tenton_quyu": "d8_L",
    "camera_params": "",
    "trigger_no": "CFD123",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 124,
    "en_name": "TP_Sample interosseous ",
    "ch_name": "足骨间肌触发点",
    "tenton_quyu": "d9_L",
    "camera_params": "",
    "trigger_no": "CFD124",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 125,
    "en_name": "TP_Abductor hallucis ",
    "ch_name": "展肌触发点",
    "tenton_quyu": "d11_L,d13_L,d14_L",
    "camera_params": "",
    "trigger_no": "CFD125",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 126,
    "en_name": "TP_Abductor digiti minimi ",
    "ch_name": "小趾展肌触发点",
    "tenton_quyu": "d4_L,d5_L,d3_L",
    "camera_params": "",
    "trigger_no": "CFD126",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 127,
    "en_name": "TP_Flexor digitorum ",
    "ch_name": "趾短屈肌触发点",
    "tenton_quyu": "d16_L",
    "camera_params": "",
    "trigger_no": "CFD127",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 128,
    "en_name": "TP_Quadratus plantae ",
    "ch_name": "足底方肌触发点",
    "tenton_quyu": "d21_L",
    "camera_params": "",
    "trigger_no": "CFD128",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 129,
    "en_name": "TP_Adductor hallucis",
    "ch_name": "收肌触发点",
    "tenton_quyu": "d16_L,d17_L",
    "camera_params": "",
    "trigger_no": "CFD129",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 130,
    "en_name": "TP_Flexor hallucis ",
    "ch_name": "短屈肌触发点",
    "tenton_quyu": "d15_L,d18_L",
    "camera_params": "",
    "trigger_no": "CFD130",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  },
  {
    "trigger_id": 131,
    "en_name": "TP_Flexor digiti minimi brevis ",
    "ch_name": "小趾短屈肌触发点",
    "tenton_quyu": "d19_L",
    "camera_params": "",
    "trigger_no": "CFD131",
    "isOpen": true,
    "isShow": false,
    "children": [],
    "noun_no": "QUYU0007"
  }
];
